name: Secure Code Review Pipeline

on:
  push:
  pull_request:

jobs:
 
  semgrep:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config auto.

bandit:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r .

gitleaks:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2

dependency-check:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: VulnerableApp
        path: .
        format: HTML

sonarqube:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v7
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
